version: '3.8'

services:
  frontend:
    build:
      context: ./ClientApp
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - app-network

  backend:
    build:
      context: ./WebApi
    container_name: backend
    ports:
      - "5000:80"
    networks:
      - app-network
    depends_on:
      - mssql
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=mssql;Database=AppDB;User=sa;Password=YourStrong!Passw0rd;

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - app-network
    volumes:
      - ./data:/var/opt/mssql

networks:
  app-network:
    driver: bridge
