version: '3.8'

services:
  frontend:
    image: frontend-app
    build:
      context: .  # Контекст для сборки фронтенда
      dockerfile: ClientApp/Dockerfile
    ports:
      - "80:80"
    networks:
      - my-network

  backend:
    image: backend-app
    build:
      context: .  # Контекст для сборки бэкенда
      dockerfile: WebApi/Dockerfile
    ports:
      - "5000:80"  # Порт 80 внутри контейнера будет проброшен на 5000 на хосте
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - my-network
    depends_on:
      - mssql

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: ${{ secrets.MSSQL_PASSWORD }}
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
