version: '3.8'

services:
  frontend:
    container_name: frontend
    build:
      context: .  # Указывает на корневую папку проекта
      dockerfile: ClientApp/Dockerfile
    ports:
      - "80:80"
    networks:
      - my-network

  backend:
    container_name: backend
    build:
      context: .  # Указывает на корневую папку проекта
      dockerfile: WebApi/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DbConnection=Server=localhost,1433;Database=PetProtector;User Id=sa;Password=StrongPa$$w0rd2024!;TrustServerCertificate=True;
    networks:
      - my-network
    depends_on:
      - mssql

  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "StrongPa$$w0rd2024!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
