version: '3.8'

services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ClientApp/Dockerfile
    ports:
      - "80:80"
      - "443:443"  # Открываем порт для HTTPS
    networks:
      - my-network

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DbConnection=Server=mssql,1433;Database=PetProtector;User Id=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=True;
    networks:
      - my-network
    depends_on:
      - mssql

  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
