name: Build and Deploy Backend

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
concurrency:
  group: deploy-group
  cancel-in-progress: false  # Не отменять текущий деплой, новый будет ждать

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'

      - name: Build the application
        run: |
          cd WebApi
          dotnet build --configuration Release

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to server via SSH
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASS }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          MSSQL_PASSWORD: ${{ secrets.MSSQL_PASSWORD }}
          REDIS_CONN: ${{ secrets.REDIS_CONN }}
          YANDEX_CLIENT_ID: ${{ secrets.YANDEX_CLIENT_ID }}
          YANDEX_CLIENT_SECRET: ${{ secrets.YANDEX_CLIENT_SECRET }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_LOGIN: ${{ secrets.SMTP_LOGIN }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          REDIS_PASS: ${{ secrets.REDIS_PASS }}
        
        run: |
          sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no $SSH_USERNAME@$SERVER_IP "
            cd /home/PetProtector &&
            export MSSQL_SA_PASSWORD=\"$MSSQL_PASSWORD\" &&
            export SMTP_SERVER=\"$SMTP_SERVER\" &&
            export SMTP_PORT=\"$SMTP_PORT\" &&
            export SMTP_LOGIN=\"$SMTP_LOGIN\" &&
            export SMTP_PASS=\"$SMTP_PASS\" &&
            export JWT_SECRET=\"$JWT_SECRET\" &&
            export REDIS_CONN=\"$REDIS_CONN\" &&
            export YANDEX_CLIENT_ID=\"$YANDEX_CLIENT_ID\" &&
            export YANDEX_CLIENT_SECRET=\"$YANDEX_CLIENT_SECRET\" &&
            export REDIS_PASS=\"$REDIS_PASS\" &&
            git pull &&
            docker-compose stop backend &&
            docker-compose rm -f backend &&
            docker-compose up --build -d backend
          "