name: Build and Deploy Backend

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Возможность ручного запуска

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0'

      - name: Build the backend application
        working-directory: ./WebApi
        run: dotnet build --configuration Release

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to server via SSH
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASS }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        run: |
          sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no $SSH_USERNAME@$SERVER_IP "
            cd /home/PetProtector &&  # Перейти в директорию бэкенда
            git pull &&
            docker-compose down &&
            docker-compose up -d backend
          "
