name: Build and Deploy React App

on:
  push:
    branches:
      - main
  workflow_dispatch: # Возможность ручного запуска

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        working-directory: ./ClientApp # Убедитесь, что это правильная директория
        run: npm install

      - name: Build the application
        working-directory: ./ClientApp # Убедитесь, что это правильная директория
        run: npm run build

  deploy:
    needs: build # Этап deploy зависит от успешного завершения build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to server via SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SERVER_IP: ${{ secrets.SERVER_IP }}  # Скрытый IP адрес
        run: |
          ssh -o StrictHostKeyChecking=no $SSH_USERNAME@$SERVER_IP "
            cd /var/www/app &&
            git pull &&
            docker-compose down &&
            docker-compose up --build -d
          "
